# .github/workflows/build.yml

name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out your repository code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Cache the 'obj' directory (Optional but recommended)
    - name: Cache build objects
      id: cache-objects
      uses: actions/cache@v4
      with:
        path: obj
        key: ${{ runner.os }}-build-${{ hashFiles('**/Makefile', '**/src/*.cpp', '**/include/*.h') }}

    # 3. Build the project using the Makefile
    - name: Build with make
      run: make

    # 4. Run the program with a capacity argument
    - name: Run the program
      run: ./bin/hybrid_cache 10 # <-- THE FIX IS HERE
